# cloudbuild.yaml
# Modular Cloud Build with action support: deploy_platform, add_app, remove_app
timeout: 60m
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _TARGETS: "frontend,backend"
  _ACTION: "deploy_platform"  # deploy_platform | add_app | remove_app
  _PROGRESS_URL: "https://maurita-unfaceted-prospectively.ngrok-free.dev"

steps:
  # 0) Context
  - id: context
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "PROJECT_ID   : ${PROJECT_ID}"
        echo "_TARGETS     : ${_TARGETS}"
        echo "_ACTION      : ${_ACTION}"
        echo "_PROGRESS_URL: ${_PROGRESS_URL:-<empty>}"
        echo "BRANCH       : ${BRANCH_NAME:-n/a}"
        echo "SHORT_SHA    : ${SHORT_SHA:-n/a}"

  ########################
  # 1) FRONTEND (≈20s)
  ########################
  - id: notify-frontend-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",frontend,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=frontend&status=START" || true
        fi
    waitFor: ['-']

  - id: frontend
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",frontend,"* ]]; then
          echo "=== FRONTEND selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[frontend] removing..."
            sleep 10
            echo "[frontend] removed."
          else
            echo "[frontend] building..."
            sleep 10
            echo "[frontend] deploying..."
            sleep 10
            echo "[frontend] done."
          fi
        else
          echo "skip frontend"
        fi

  - id: notify-frontend-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",frontend,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=frontend&status=DONE" || true
        fi
    waitFor: ['frontend']

  ########################
  # 2) BACKEND (≈24s)
  ########################
  - id: notify-backend-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",backend,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=backend&status=START" || true
        fi
    waitFor: ['notify-frontend-done']

  - id: backend
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",backend,"* ]]; then
          echo "=== BACKEND selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[backend] removing..."
            sleep 12
            echo "[backend] removed."
          else
            echo "[backend] building..."
            sleep 12
            echo "[backend] deploying..."
            sleep 12
            echo "[backend] done."
          fi
        else
          echo "skip backend"
        fi

  - id: notify-backend-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",backend,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=backend&status=DONE" || true
        fi
    waitFor: ['backend']

  ########################
  # 3) GITEA (≈16s)
  ########################
  - id: notify-gitea-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",gitea,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=gitea&status=START" || true
        fi
    waitFor: ['notify-backend-done']

  - id: gitea
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",gitea,"* ]]; then
          echo "=== GITEA selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[gitea] removing..."
            sleep 8
            echo "[gitea] removed."
          else
            echo "[gitea] setup..."
            sleep 8
            echo "[gitea] finishing..."
            sleep 8
            echo "[gitea] done."
          fi
        else
          echo "skip gitea"
        fi

  - id: notify-gitea-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",gitea,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=gitea&status=DONE" || true
        fi
    waitFor: ['gitea']

  ########################
  # 4) CONFLUENCE (≈16s)
  ########################
  - id: notify-confluence-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",confluence,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=confluence&status=START" || true
        fi
    waitFor: ['notify-gitea-done']

  - id: confluence
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",confluence,"* ]]; then
          echo "=== CONFLUENCE selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[confluence] removing..."
            sleep 8
            echo "[confluence] removed."
          else
            echo "[confluence] setup..."
            sleep 8
            echo "[confluence] finishing..."
            sleep 8
            echo "[confluence] done."
          fi
        else
          echo "skip confluence"
        fi

  - id: notify-confluence-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",confluence,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=confluence&status=DONE" || true
        fi
    waitFor: ['confluence']

  ########################
  # 5) JIRA (≈16s)
  ########################
  - id: notify-jira-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",jira,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=jira&status=START" || true
        fi
    waitFor: ['notify-confluence-done']

  - id: jira
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",jira,"* ]]; then
          echo "=== JIRA selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[jira] removing..."
            sleep 8
            echo "[jira] removed."
          else
            echo "[jira] setup..."
            sleep 8
            echo "[jira] finishing..."
            sleep 8
            echo "[jira] done."
          fi
        else
          echo "skip jira"
        fi

  - id: notify-jira-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",jira,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=jira&status=DONE" || true
        fi
    waitFor: ['jira']

  ########################
  # 6) ARTIFACTORY (≈18s)
  ########################
  - id: notify-artifactory-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",artifactory,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=artifactory&status=START" || true
        fi
    waitFor: ['notify-jira-done']

  - id: artifactory
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",artifactory,"* ]]; then
          echo "=== ARTIFACTORY selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[artifactory] removing..."
            sleep 9
            echo "[artifactory] removed."
          else
            echo "[artifactory] building..."
            sleep 9
            echo "[artifactory] deploying..."
            sleep 9
            echo "[artifactory] done."
          fi
        else
          echo "skip artifactory"
        fi

  - id: notify-artifactory-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",artifactory,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=artifactory&status=DONE" || true
        fi
    waitFor: ['artifactory']

  ########################
  # 7) GITHUB (≈18s)
  ########################
  - id: notify-github-start
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",github,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=github&status=START" || true
        fi
    waitFor: ['notify-artifactory-done']

  - id: github
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [[ ",${_TARGETS}," == *",github,"* ]]; then
          echo "=== GITHUB selected (action: ${_ACTION}) ==="
          if [ "${_ACTION}" = "remove_app" ]; then
            echo "[github] removing..."
            sleep 9
            echo "[github] removed."
          else
            echo "[github] building..."
            sleep 9
            echo "[github] deploying..."
            sleep 9
            echo "[github] done."
          fi
        else
          echo "skip github"
        fi

  - id: notify-github-done
    name: curlimages/curl
    entrypoint: sh
    args:
      - -c
      - |
        if [ -n "${_PROGRESS_URL}" ] && echo ",${_TARGETS}," | grep -q ",github,"; then
          curl -sS -m 2 -X POST "${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=github&status=DONE" || true
        fi
    waitFor: ['github']