# cloudbuild.yaml (fragmentele cu sleep mai mari)

# 1) FRONTEND
- id: notify-frontend-start
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",frontend,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=frontend&status=START\" || true; fi"]
  waitFor: ['-']

- id: frontend
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ ",${_TARGETS}," == *",frontend,"* ]]; then
        echo "=== FRONTEND selected ==="
        echo "[frontend] building..."
        sleep 3
        echo "[frontend] deploying..."
        sleep 3
        echo "[frontend] done."
      else
        echo "skip frontend"
      fi

- id: notify-frontend-done
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",frontend,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=frontend&status=DONE\" || true; fi"]
  waitFor: ['frontend']

# 2) BACKEND (8s total)
- id: notify-backend-start
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",backend,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=backend&status=START\" || true; fi"]
  waitFor: ['frontend']

- id: backend
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ ",${_TARGETS}," == *",backend,"* ]]; then
        echo "=== BACKEND selected ==="
        echo "[backend] building..."
        sleep 4
        echo "[backend] deploying..."
        sleep 4
        echo "[backend] done."
      else
        echo "skip backend"
      fi

- id: notify-backend-done
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",backend,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=backend&status=DONE\" || true; fi"]
  waitFor: ['backend']

# 3) GITEA (6s) – waitFor backend
- id: notify-gitea-start
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",gitea,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=gitea&status=START\" || true; fi"]
  waitFor: ['backend']

- id: gitea
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ ",${_TARGETS}," == *",gitea,"* ]]; then
        echo "=== GITEA selected ==="
        echo "[gitea] setup..."
        sleep 3
        echo "[gitea] finishing..."
        sleep 3
        echo "[gitea] done."
      else
        echo "skip gitea"
      fi

- id: notify-gitea-done
  name: curlimages/curl
  entrypoint: sh
  args: ["-c", "if [ -n \"${_PROGRESS_URL}\" ] && echo \",${_TARGETS},\" | grep -q \",gitea,\"; then curl -sS -m 2 -X POST \"${_PROGRESS_URL}/progress?op=${BUILD_ID}&step=gitea&status=DONE\" || true; fi"]
  waitFor: ['gitea']

# 4) CONFLUENCE (6s) – waitFor gitea
# ... identic: 3s + 3s sleep (vezi mai sus)

# 5) JIRA (6s) – waitFor confluence
# ... identic: 3s + 3s sleep
